set :deploy_config_path, 'deploy/deploy.rb'
set :stage_config_path, 'deploy/environments'

require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/scm/git"

install_plugin Capistrano::SCM::Git

Dir.glob("tasks/*.rb").each { |r| import r }