name: Build Backopper
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          curl -L -s https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -o $(dirname $GITHUB_WORKSPACE)/bin/dep
          chmod +x $(dirname $GITHUB_WORKSPACE)/bin/dep
          export PATH="$PATH:$(dirname $GITHUB_WORKSPACE)/bin/"

      - name: Install dependencies
        run: dep ensure

      - name: Build
        run: go build -v .
