name: Backopper
on:
  push:
    branches:
      - feature/go-rewrite
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install godep
        run: |
          mkdir -p $HOME/go/bin

          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Get dependencies
        run: |
          export GOBIN="$HOME/go/bin"
          export GOPATH="$HOME/work"
          export PATH=$PATH:$GOBIN

          go get -v -t -d ./...

          dep ensure

      - name: Build
        run: go build -v .
